### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [corphish/TextTools#1]
as the APK in https://github.com/corphish/TextTools/releases/tag/v1.0.6 is not built from the tagged commit

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6524891933#L799

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c94534e04bf2c9706c7c51b215d520f9c2df71de

**Comment by corphish** [comment]
Updated the release apk, built from tagged commit. Can you please confirm whether FDroid can now build it or not?

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/01edd14cd038e160c05741e4b287f49759df7ea8
