### ISSUE TITLE
FR: ability to disable context menus

### ISSUE THREAD

**Issue by sming** [corphish/TextTools#10]
Hi there , I love the idea of the app, but for me, sadly, it was an instant uninstall, because it basically polluted my context menu with things I will never use such as the WhatsApp phone call functionality. If you could add check boxes to each of the functions, that would be awesome. 

This app seems to have great potential, and you've done a great job so far, keep it up!

**Comment by corphish** [comment]
You should try the single variant (app-release-single.apk in the releases section). This will provide you with only 1 option (Text Tools) in the context menu, which will then reveal all the supported options in the apps own UI, which keeps the context menu clean.

Having check boxes to let users what they want in the context menu would be difficult as the context menu entries have to be defined in manifest, and in manifest I am not sure if we can read user preferences to enable/disable an option.

**Comment by corphish** [comment]
Turns out, it is possible to achieve this. Same has been added in https://github.com/corphish/TextTools/releases/tag/v2.0.0.

**Comment by corphish** [comment]
Closing this as the FR has been added in v2.0.0.
