### ISSUE TITLE
Add camel case text transform

### ISSUE THREAD

**Issue by czarnyckm** [corphish/TextTools#11]
It will be good, that transform text include possibility to  capitalize the first letter of each word.

**Comment by corphish** [comment]
Already present as "Title Case (All words)"

**Comment by davidpiano** [comment]
"Camel case" means `wordsThatAreStuckTogether` like that. I think maybe camel case should **_not_** be a TextTools feature, because trying to guess the word boundaries seems like it would be error-prone. I could be wrong about that.
